#! /usr/bin/env python3

import csv, re, sys

pat = re.compile(".*\[(.*)\]")
fix = lambda s: s.replace(' ', '-').replace('-+-', '+')

sysdict = dict()
syslist = []
csvfile = None
reader = None

def open_or_rewind():
    global csvfile, reader, sysdict, syslist
    csvfile = open('compdeps.csv')
    reader = csv.reader(csvfile)
    header = reader.__next__()[3:]
    if len(syslist) == 0:
        pass

# Read and parse the header line.
for sysname in reader.__next__()[3:]:
    m = pat.match(sysname)
    s = m[1] if m else sysname
    s = fix(s)
    sysdict[s] = 0
    syslist.append(s)

# Find all self-reported circular dependencies
out = open("self-reported.txt", "w")
for line in reader:
    me = fix(line[2])
    if me not in sysdict:
        print(f"***{me} not found", file=sys.stderr)
    line = line[3:]
    for i in range(0, len(line)):
        if line[i].find(',') != -1:
            print(f"{me} : {syslist[i]}", file=out)
    #print(me, line)
out.close()

# Find all multiple entries
open_or_rewind()
for line in reader:
    me = fix(line[2])
    syslist[me] += 1
dups = [ sysdict[k] for k in sysdict.keys() if sysdict[k] > 1 ]
for d in dups:
    print(f"{d}")
